https://youtu.be/vYuhA1rQkaM Joe_Cocker-Unchain_My_Heart
https://youtu.be/uSiHqxgE2d0 Ray_Charles-Hit_The_Road_Jack
https://youtu.be/otCpCn0l4Wo M.C.Hammer-UCan't_Touch_This
https://youtu.be/djV11Xbc914 a-ha-Take_On_Me
https://youtu.be/OMOGaugKpzs ThePolice-Every_Breath_You_Take
https://youtu.be/n4RjJKxsamQ Scorpions-Wind_of_Change
https://youtu.be/fJ9rUzIMcZQ Queen–Bohemian_Rhapsody
https://youtu.be/Zi_XLOBDo_Y Michael_Jackson-Billie_Jean
https://youtu.be/9jK-NcRmVcw Europe-The_Final_Countdown
https://youtu.be/Rbm6GXllBiw GunsN'Roses-Paradise_City
https://youtu.be/xwtdhWltSIg R.E.M.-Losing_My_Religion
https://youtu.be/oRdxUFDoQe0 Michael_Jackson-Beat_It
https://youtu.be/v2AC41dglnM AC/DC-Thunderstruck
https://youtu.be/dsUXAEzaC3Q Michael_Jackson-Bad
https://youtu.be/HzZ_urpj4As Michael_Jackson-The_Way_You_Make_Me
https://youtu.be/pAgnJDJN4VA AC/DC-Back_In_Black
https://youtu.be/YR5ApYxkU-U Pink_Floyd-Another_Brick_In_The_Wall
https://youtu.be/eM8Ss28zjcE Queen-I_Want_To_Break_Free
https://youtu.be/Qt2mbGP6vFI Phil_Collins-Another_Day_In_Paradise
https://youtu.be/t1TcDHrkQYg Alphaville-Forever_Young
https://youtu.be/loWXMtjUZWM Foreigner-I_want_to
https://youtu.be/izGwDsrQ1eQ George_Michael-Careless_Whisper
https://youtu.be/FTQbiNvZqaY Toto-Africa
https://youtu.be/KrZHPOeOxQQ BonJovi-You_Give_Love_ABad_Name
https://youtu.be/rY0WxgSXdEE Queen-Another_One_Bites_theDust
https://youtu.be/pIgZ7gMze7A Wham!-Wake_Me_Up
https://youtu.be/qeMFqkcPYcg Eurythmics-Sweet_Dreams
https://youtu.be/eH3giaIzONA Whitney_Houston-I_Wanna_Dance
https://youtu.be/GOJk0HW_hJw Whitesnake-Is_This_Love
https://youtu.be/WGU_4-5RaxU Blondie-Heart_of_Glass
https://youtu.be/9f06QZCVUHg Bryan_Adams-Summer_of’69
https://youtu.be/CdqoNKCCt7A Simple_Minds-Don't_You
https://youtu.be/hCuMWrfXG4E Billy_Joel-Uptown_Girl
https://youtu.be/J9gKyRmic20 Crowded_House-Don't_Dream
https://youtu.be/fPO76Jlnz6c Coolio-Gangsta's_Paradise
https://youtu.be/hTWKbfoikeg Nirvana-Smells_Like_Teen_Spirit
https://youtu.be/Y0pdQU87dc8 Bryan_Adams-Everything_I_Do
https://youtu.be/6Ejga4kJUts TheCranberries-Zombie
https://youtu.be/tAGnKpE4NCI Metallica:Nothing_Else_Matters
https://youtu.be/1lyu1KKwC74 The_Verve-Bitter_Sweet_Symphony
https://youtu.be/QNJL6nfu__Q Michael_Jackson-They_Don’t_Care
https://youtu.be/NKMtZm2YuBE Puff_Daddy-I'll_be_Missing_You
https://youtu.be/CD-E-LDc384 Metallica:Enter_Sandman
https://youtu.be/ZJL4UGSbeFg Shania_Twain-I_Feel_Like_A_Woman
https://youtu.be/mzJj5-lubeM Red_Hot_Chili_Peppers-Scar_Tissue
https://youtu.be/YP3W-E0OamU Michael_Jackson-Black_or_White
https://youtu.be/gJLIiF15wjQ Spice_Girls-Wannabe
https://youtu.be/C3lWwBslWqg Sting-Desert_Rose
https://youtu.be/mOYZaiDZ7BM Rednex-Cotton_Eye_Joe
https://youtu.be/d73tiBBzvFM Ace_of_Base-All_That_She_Wants
https://youtu.be/YlUKcNNmywk Red_Hot_Chili_Peppers-Californication
https://youtu.be/PCTI_e81DtM TheProdigy-Smack_My_BitchUp
https://youtu.be/nllmm7Q4sj0 TheProdigy-Breathe
https://youtu.be/uCM_4J6xdKg TheProdigy-Diesel_Power
https://youtu.be/psCf0oK9dvg TheProdigy-Funky_Shit
https://youtu.be/76ZRlYlyVu0 TheProdigy-Serial_Thrilla
https://youtu.be/rMbyJnLOhCM TheProdigy-Mindfiels
https://youtu.be/iU5UKGTk-XI TheProdigy-Narayan
https://youtu.be/_SUY0ujOenU TheProdigy-Firestarter
https://youtu.be/HuZTEsvgQko TheProdigy-Climbatize
https://youtu.be/sf3QD3VoOnU TheProdigy-Fuel_My_Fire
https://youtu.be/c18441Eh_WE Kylie_Minogue-Can't_Get_You
https://youtu.be/63vqob-MljQ Kylie_Minogue-Come_Into_My_World
https://youtu.be/vx2u5uUu3DE BonJovi-It's_My_Life
https://youtu.be/d27gTrPPAyk Sting-Englishman_In_NewYork
https://youtu.be/mqFLXayD6e8 Shania_Twain-That_Don't_Impress_Me_Much
https://youtu.be/llyiQ4I-mcQ Vengaboys-Boom,Boom,Boom!!
https://youtu.be/HCm6gRHINqA Savage_Garden-To_The_Moon&Back
https://youtu.be/ymNFyxvIdaM BomfunkMC's-Freestyler
https://youtu.be/NI6aOFI7hms TheCardigans-Lovefool
https://youtu.be/6W5pq4bIzIw Shaggy-Boombastic
https://youtu.be/lN_MSyrq6-U TheGlitch_Mob/DaftPunk:Rerezzed
