https://youtu.be/vYuhA1rQkaM Joe_Cocker-Unchain_My_Heart
https://youtu.be/uSiHqxgE2d0 Ray_Charles-Hit_The_Road_Jack
https://youtu.be/otCpCn0l4Wo M.C.Hammer-UCan't_Touch_This
https://youtu.be/djV11Xbc914 a-ha-Take_On_Me
https://youtu.be/OMOGaugKpzs ThePolice-Every_Breath_You_Take
https://youtu.be/n4RjJKxsamQ Scorpions-Wind_of_Change
https://youtu.be/fJ9rUzIMcZQ Queen–Bohemian_Rhapsody
https://youtu.be/Zi_XLOBDo_Y Michael_Jackson-Billie_Jean
https://youtu.be/9jK-NcRmVcw Europe-The_Final_Countdown
https://youtu.be/Rbm6GXllBiw GunsN'Roses-Paradise_City
https://youtu.be/xwtdhWltSIg R.E.M.-Losing_My_Religion
https://youtu.be/oRdxUFDoQe0 Michael_Jackson-Beat_It
https://youtu.be/v2AC41dglnM AC/DC-Thunderstruck
https://youtu.be/dsUXAEzaC3Q Michael_Jackson-Bad
https://youtu.be/HzZ_urpj4As Michael_Jackson-The_Way_You_Make_Me
https://youtu.be/pAgnJDJN4VA AC/DC-Back_In_Black
https://youtu.be/YR5ApYxkU-U Pink_Floyd-Another_Brick_In_The_Wall
https://youtu.be/eM8Ss28zjcE Queen-I_Want_To_Break_Free
https://youtu.be/Qt2mbGP6vFI Phil_Collins-Another_Day_In_Paradise
https://youtu.be/t1TcDHrkQYg Alphaville-Forever_Young
https://youtu.be/loWXMtjUZWM Foreigner-I_want_to
https://youtu.be/izGwDsrQ1eQ George_Michael-Careless_Whisper
https://youtu.be/FTQbiNvZqaY Toto-Africa
https://youtu.be/KrZHPOeOxQQ BonJovi-You_Give_Love_ABad_Name
https://youtu.be/rY0WxgSXdEE Queen-Another_One_Bites_theDust
https://youtu.be/pIgZ7gMze7A Wham!-Wake_Me_Up
https://youtu.be/qeMFqkcPYcg Eurythmics-Sweet_Dreams
https://youtu.be/eH3giaIzONA Whitney_Houston-I_Wanna_Dance
https://youtu.be/GOJk0HW_hJw Whitesnake-IsThisLove
https://youtu.be/WGU_4-5RaxU Blondie-HeartOfGlass
https://youtu.be/9f06QZCVUHg BryanAdams-SummerOf’69
https://youtu.be/CdqoNKCCt7A SimpleMinds-Don'tYou
https://youtu.be/hCuMWrfXG4E BillyJoel-UptownGirl
https://youtu.be/J9gKyRmic20 CrowdedHouse-Don'tDream
https://youtu.be/fPO76Jlnz6c Coolio-Gangsta'sParadise
https://youtu.be/hTWKbfoikeg Nirvana-SmellsLikeTeenSpirit
https://youtu.be/Y0pdQU87dc8 BryanAdams-EverythingIDo
https://youtu.be/6Ejga4kJUts TheCranberries-Zombie
https://youtu.be/tAGnKpE4NCI Metallica:NothingElseMatters
https://youtu.be/1lyu1KKwC74 TheVerve-BitterSweetSymphony
https://youtu.be/QNJL6nfu__Q MichaelJackson-TheyDon’tCare
https://youtu.be/NKMtZm2YuBE PuffDaddy-I'llBeMissingYou
https://youtu.be/CD-E-LDc384 Metallica:EnterSandman
https://youtu.be/ZJL4UGSbeFg ShaniaTwain-IFeelLikeAWoman
https://youtu.be/mzJj5-lubeM RedHotChiliPeppers-ScarTissue
https://youtu.be/YP3W-E0OamU MichaelJackson-BlackorWhite
https://youtu.be/gJLIiF15wjQ SpiceGirls-Wannabe
https://youtu.be/C3lWwBslWqg Sting-DesertRose
https://youtu.be/mOYZaiDZ7BM Rednex-CottonEyeJoe
https://youtu.be/d73tiBBzvFM AceofBase-AllThatSheWants
https://youtu.be/YlUKcNNmywk RedHotChiliPeppers-Californication
https://youtu.be/PCTI_e81DtM TheProdigy-SmackMyBitchUp
https://youtu.be/nllmm7Q4sj0 TheProdigy-Breathe
https://youtu.be/uCM_4J6xdKg TheProdigy-DieselPower
https://youtu.be/psCf0oK9dvg TheProdigy-FunkyShit
https://youtu.be/76ZRlYlyVu0 TheProdigy-SerialThrilla
https://youtu.be/rMbyJnLOhCM TheProdigy-Mindfiels
https://youtu.be/iU5UKGTk-XI TheProdigy-Narayan
https://youtu.be/_SUY0ujOenU TheProdigy-Firestarter
https://youtu.be/HuZTEsvgQko TheProdigy-Climbatize
https://youtu.be/sf3QD3VoOnU TheProdigy-FuelMyFire
https://youtu.be/c18441Eh_WE KylieMinogue-Can'tGetYou
https://youtu.be/63vqob-MljQ KylieMinogue-ComeIntoMyWorld
https://youtu.be/vx2u5uUu3DE BonJovi-It'sMyLife
https://youtu.be/d27gTrPPAyk Sting-EnglishmanInNewYork
https://youtu.be/mqFLXayD6e8 ShaniaTwain-ThatDon'tImpressMeMuch
https://youtu.be/llyiQ4I-mcQ Vengaboys-Boom,Boom,Boom!!
https://youtu.be/HCm6gRHINqA SavageGarden-ToTheMoon&Back
https://youtu.be/ymNFyxvIdaM BomfunkMC's-Freestyler
https://youtu.be/NI6aOFI7hms TheCardigans-Lovefool
https://youtu.be/6W5pq4bIzIw Shaggy-Boombastic
https://youtu.be/lN_MSyrq6-U TheGlitchMob/DaftPunk:Rerezzed
